[project]
name = "version-consistency-checker"
version = "0.1.0"
description = "Check version consistency between Nix devshell and others"
readme = "README.md"
requires-python = "==3.14.3"
dependencies = [
  "pydantic==2.12.5",
  "typer==0.24.1",
]

[project.scripts]
version-consistency-checker = "version_consistency_checker:main"
vcc = "version_consistency_checker:main"

[dependency-groups]
dev = [
  "pytest==9.0.2",
  "pytest-cov==7.0.0",
  "ruff==0.15.4",
  "ty==0.0.20",
]

[build-system]
requires = ["uv_build==0.10.7"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
